pipeline{
    agent any
    stages{
        stage('Greet'){
            steps{
                echo 'Hello world'
            }
        }
        stage('Build'){
            steps{
                echo 'Building app'
            }
        }
        stage('Test'){
            steps{
                echo 'Testing app'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploying app'
            }
        stage('Testing'){
            steps{
                echo 'Testing it out'
            }
        }
        }
    }
    post{
        success{
            echo 'Pipeline succeeded'
        }
        failure{
            echo 'Pipeline failed'
        }
    }
}

